;;; indium-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from indium-breakpoint.el

(register-definition-prefixes "indium-breakpoint" '("indium-breakpoint-"))


;;; Generated autoloads from indium-chrome.el

(register-definition-prefixes "indium-chrome" '("indium-"))


;;; Generated autoloads from indium-client.el

(register-definition-prefixes "indium-client" '("indium-client-"))


;;; Generated autoloads from indium-debugger.el

(register-definition-prefixes "indium-debugger" '("indium-debugger-"))


;;; Generated autoloads from indium-debugger-litable.el

(register-definition-prefixes "indium-debugger-litable" '("indium-debugger-litable-"))


;;; Generated autoloads from indium-debugger-locals.el

(register-definition-prefixes "indium-debugger-locals" '("indium-debugger-locals"))


;;; Generated autoloads from indium-inspector.el

(register-definition-prefixes "indium-inspector" '("indium-inspector-"))


;;; Generated autoloads from indium-interaction.el

(autoload 'indium-connect "indium-interaction" "\
Open a new connection to a runtime." t)
(autoload 'indium-launch "indium-interaction" "\
Start a new process and connect to it." t)
(register-definition-prefixes "indium-interaction" '("indium-"))


;;; Generated autoloads from indium-list-sources.el

(autoload 'indium-list-sourcemap-sources "indium-list-sources" "\
Display a list of all resolved sourcemap sources." t)
(autoload 'indium-list-script-sources "indium-list-sources" "\
Display a list of all resolved script sources." t)
(register-definition-prefixes "indium-list-sources" '("indium-list-sources-"))


;;; Generated autoloads from indium-nodejs.el

(register-definition-prefixes "indium-nodejs" '("indium-"))


;;; Generated autoloads from indium-render.el

(register-definition-prefixes "indium-render" '("indium-"))


;;; Generated autoloads from indium-repl.el

(register-definition-prefixes "indium-repl" '("company-indium-repl" "indium-"))


;;; Generated autoloads from indium-scratch.el

(autoload 'indium-scratch "indium-scratch" "\
Pop to the scratch buffer.
If no scratch buffer exists for the current connection, create
one first." t)
(register-definition-prefixes "indium-scratch" '("indium-scratch-"))


;;; Generated autoloads from indium-structs.el

(register-definition-prefixes "indium-structs" '("indium-"))

;;; End of scraped data

(provide 'indium-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; indium-autoloads.el ends here
