(source gnu)
(source melpa)
(source org)

(depends-on "ace-jump-mode")
(depends-on "auctex")
(depends-on "cargo")
(depends-on "cask-mode")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "cmake-mode")
(depends-on "coffee-mode")
(depends-on "context-coloring")
(depends-on "csharp-mode")
(depends-on "d-mode")
(depends-on "dockerfile-mode")
(depends-on "elm-mode")
(depends-on "elnode")
(depends-on "evil")
(depends-on "evil-collection")
(depends-on "evil-ledger")
(depends-on "evil-magit")
(depends-on "evil-org")
(depends-on "evil-surround")
(depends-on "exec-path-from-shell")
(depends-on "fill-column-indicator")
(depends-on "floobits")
(depends-on "fontify-face")
(depends-on "fsharp-mode")
(depends-on "glsl-mode")
(depends-on "haml-mode")
(depends-on "handlebars-mode")
(depends-on "haskell-mode")
(depends-on "highlight-indent-guides")
(depends-on "ido-completing-read+")
(depends-on "ido-vertical-mode")
(depends-on "idris-mode")
(depends-on "indium")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "ledger-mode")
(depends-on "less-css-mode")
(depends-on "lsp-mode")
(depends-on "lua-mode")
;(depends-on "magit")
(depends-on "magit"
            :git "https://github.com/magit/magit.git"
            :ref "8b45756390e43bfc3247dd85bf5f7738516e569a"
            ;; Source: https://github.com/melpa/melpa/blob/master/recipes/magit
            :files ("lisp/magit"
                    "lisp/magit*.el"
                    "lisp/git-rebase.el"
                    "Documentation/magit.texi"
                    "Documentation/AUTHORS.md"
                    "LICENSE"
                    (:exclude "lisp/magit-libgit.el"
                              ;; Cannot remove this yet because it would
                              ;; also be removed from the stable version.
                              ;; "lisp/magit-section.el"
                              )))
(depends-on "markdown-mode")
(depends-on "nginx-mode")
(depends-on "nix-mode")
(depends-on "ob-async")
(depends-on "org-plus-contrib")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "python-mode")
(depends-on "rainbow-blocks")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-identifiers")
(depends-on "rjsx-mode")
(depends-on "rust-mode")
(depends-on "sass-mode")
(depends-on "scala-mode")
(depends-on "skewer-mode")
(depends-on "solarized-theme")
(depends-on "swift-mode")
(depends-on "systemd")
(depends-on "typescript-mode")
(depends-on "undo-tree")
(depends-on "web-mode")
(depends-on "with-editor")
(depends-on "yaml-mode")
