(source melpa)
(source org)

(depends-on "clojure-mode")
(depends-on "color-theme-solarized")
(depends-on "dash")
(depends-on "evil")
(depends-on "evil-surround")
(depends-on "fill-column-indicator")
(depends-on "haskell-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "org-plus-contrib")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "smart-tabs-mode")